model_selection:
  model:
    XGBRegressor:
      search_param_grid:
        max_depth:
          - 3
          - 5
          - 7
        n_estimators:
          - 200
          - 400
          - 600
        learning_rate:
          - 0.01
          - 0.05
          - 0.1
        subsample:
          - 0.7
          - 0.8
        colsample_bytree:
          - 0.7
          - 0.8
        random_state:
          - 42

    RandomForestRegressor:
      search_param_grid:
        n_estimators:
          - 200
          - 400
          - 600
        max_depth:
          - 6
          - 10
          - 14
        min_samples_split:
          - 2
          - 5
        random_state:
          - 42

    LinearRegression:
      search_param_grid:
        fit_intercept:
          - true
          - false
